alter table nodes add primary key(id);
alter table ways add primary key (id);
alter table relations add primary key (id);
create index node_tags_idx on node_tags (id);
create index nodes_tile_idx on nodes (tile);
create index way_tags_idx on way_tags (id);
create index way_nodes_way_idx on way_nodes (id);
create index way_nodes_node_idx on way_nodes (node_id);
create index relation_tags_idx on relation_tags (id);
create index relation_members_relation_idx on relation_members (id);
create index relation_members_member_idx on relation_members (m_id);
analyze nodes;
analyze node_tags;
analyze ways;
analyze way_nodes;
analyze way_tags;
analyze relations;
analyze relation_members;
analyze relation_tags;
