source 'https://rubygems.org'

gem 'rails', '3.2.9'

gem 'json'

gem 'jquery-rails'

gem 'pg'
gem 'activerecord-postgresql-adapter'
gem 'activerecord-postgis-adapter'
gem 'activerecord-postgresql-extensions'

gem 'execjs'

gem 'therubyracer'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platform => :ruby

  gem 'uglifier', '>= 1.0.3'
end
